[project]
name = "picow-ws2812-devtools"
version = "0.1.0"
description = "Development tools for WS2812 LED wall visualization"
authors = [{ name = "Giorgio Caizzi", email = "giocaizzi@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "picow-ws2812",
    "ledwall-server",
    "matplotlib>=3.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
